# Generated by Django 2.1.2 on 2018-11-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_activity_drinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='estimated_alcohol',
            field=models.FloatField(default=-1.0),
        ),
    ]
